name: main
on:
  push:
    branches:
      - main
      - staging
      - develop

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: '20.x'

jobs:
  eas-update-publish:
    name: EAS Update - Publish to Expo Go
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install dependencies
        run: npm install

      - name: Publish to Expo Go
        run: |
          cd apps/native
          eas update --auto --non-interactive

  docker-publish-back:
    name: Docker Publish - Back
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./apps/back
          push: true
          tags: soymustael/mobile-fs-mono:${{ github.ref_name }}

  docker_build_push_acr:
    name: Docker Build and Push to ACR
    needs: docker-publish-back
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Azure CLI commands
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
#      - name: Run Azure CLI commands
#        run: |
#          az containerapp up \
#            --name mobile-fs-mono \
#            --resource-group devops-personal \
#            --location francecentral \
#            --environment ${{ github.ref_name }} \
#            --image soymustael/mobile-fs-mono:${{ github.ref_name }} \
#            --target-port 3000 \
#            --ingress external \
#            --query properties.configurations.ingress.fqdn \
