name: main
on:
  push:
    branches:
      - main
      - staging
      - develop

  pull_request:
    branches:
      - main
      - staging
      - develop

env:
  NODE_VERSION: '20.x'

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install dependencies
        run: yarn

      - name: Publish to Expo Go
        run: |
          cd apps/native
          eas update --auto --non-interactive --release-channel ${{ github.ref }}
      #          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
      #            expo publish apps/native --non-interactive --release-channel main
      #          elif [ ${{ github.ref }} = 'refs/heads/staging' ]; then
      #            expo publish apps/native --non-interactive --release-channel staging
      #          elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
      #            eas update apps/native --non-interactive --release-channel develop
      #          fi

      - name: Add Expo Link to PR
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ## Test this PR with Expo Go
            ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://exp.host/@soymusta/mobile-fs-mono?release-channel=pr-${{ github.event.number }})
            **------ Build published to [Expo](https://exp.host/@andreaslydemann/todo-app?release-channel=pr-${{ github.event.number }}) ------**